### ISSUE TITLE
bug: Filter Punishment duration stuck on permanent

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#572] opened 2019-11-24 16:11 UTC
The punishment duration is set to 1h, but it shows as permanent (altho it actually isnt)

![image](https://user-images.githubusercontent.com/30398469/69497434-28c47800-0f31-11ea-9931-b74e6f86f3ea.png)

**Comment by kyranet** [comment] 2019-11-24 16:11
Duplicate of #540

**Closed as completed by kyranet** 2019-11-24 16:11 UTC
